In [1]:
import pandas as pd
from IPython.display import display, Markdown

results_path = "../results"

tables = {
    "1. Model Building Comparison": "model_building_comparison.csv",
    "2. Hyperparameter Tuning Results": "CKD_hyperparameter_tuning_results.csv",
    "3. Model Evaluation Results": "CKD_Model_Evaluation_FAST.csv",
    "4. Final Test Evaluation After Tuning": "CKD_final_test_evaluation_after_tuning.csv",
    "5. Tuning and Evaluation Combined": "CKD_tuning_and_evaluation_combined.csv",
    "6. Dashboard Model Results": "dashboard_model_results.csv"
}

for title, filename in tables.items():

    display(Markdown(f"## {title}"))

    df = pd.read_csv(f"{results_path}/{filename}")

    # Round numerical columns
    df = df.round(4)

    display(df)

## 1. Model Building Comparison

,Model,Training Accuracy,Training Precision,Training Recall,Training F1-Score,Training ROC-AUC,CV Mean Accuracy,CV Std,CV Fold 1,CV Fold 2,CV Fold 3,CV Fold 4,CV Fold 5,Generalization Gap
0,SVM,1.0000,1.0000,1.0,1.0000,1.0000,0.9969,0.0062,1.0000,1.0000,1.0000,1.0000,0.9844,0.0031
1,Logistic Regression,1.0000,1.0000,1.0,1.0000,1.0000,0.9938,0.0077,1.0000,1.0000,0.9844,0.9844,1.0000,0.0062
2,Random Forest,1.0000,1.0000,1.0,1.0000,1.0000,0.9906,0.0077,1.0000,0.9844,0.9844,0.9844,1.0000,0.0094
3,AdaBoost,1.0000,1.0000,1.0,1.0000,1.0000,0.9906,0.0125,1.0000,0.9844,0.9688,1.0000,1.0000,0.0094
4,LightGBM,1.0000,1.0000,1.0,1.0000,1.0000,0.9844,0.0171,0.9844,0.9844,0.9531,1.0000,1.0000,0.0156
5,XGBoost,0.9969,0.9950,1.0,0.9975,1.0000,0.9812,0.0182,1.0000,0.9844,0.9531,0.9688,1.0000,0.0156
6,Gradient Boosting,1.0000,1.0000,1.0,1.0000,1.0000,0.9750,0.0272,0.9844,0.9844,0.9219,0.9844,1.0000,0.0250
7,KNN,1.0000,1.0000,1.0,1.0000,1.0000,0.9625,0.0125,0.9531,0.9844,0.9531,0.9531,0.9688,0.0375
8,Decision Tree,0.9906,0.9852,1.0,0.9926,0.9993,0.9531,0.0171,0.9375,0.9531,0.9531,0.9375,0.9844,0.0375

## 2. Hyperparameter Tuning Results

,Model,Best_CV_F1,Mean_Train_F1,Train_CV_Gap,Best_Params,Generalization_Diagnostic
0,Logistic Regression,0.9951,1.0000,0.0049,"{'model__solver': 'lbfgs', 'model__C': 10.0}",No strong warning from train-CV gap
1,Random Forest,0.9951,0.9981,0.0031,"{'model__n_estimators': 75, 'model__min_sample...",No strong warning from train-CV gap
2,SVM,0.9949,1.0000,0.0051,"{'model__gamma': 0.1, 'model__C': 1.0}",No strong warning from train-CV gap
3,AdaBoost,0.9925,1.0000,0.0075,"{'model__n_estimators': 50, 'model__learning_r...",No strong warning from train-CV gap
4,XGBoost,0.9901,0.9988,0.0086,"{'model__subsample': 0.8, 'model__n_estimators...",No strong warning from train-CV gap
5,LightGBM,0.9874,1.0000,0.0126,"{'model__num_leaves': 31, 'model__n_estimators...",No strong warning from train-CV gap
6,Gradient Boosting,0.9827,0.9957,0.0130,"{'model__n_estimators': 75, 'model__min_sample...",No strong warning from train-CV gap
7,KNN,0.9793,0.9873,0.0081,"{'model__weights': 'uniform', 'model__p': 1, '...",No strong warning from train-CV gap
8,Decision Tree,0.9752,0.9975,0.0223,"{'model__min_samples_split': 2, 'model__min_sa...",No strong warning from train-CV gap

## 3. Model Evaluation Results

                 Model  Accuracy  Precision  Recall  F1-score  ROC-AUC
0        Random Forest    1.0000        1.0    1.00    1.0000   1.0000
1             LightGBM    1.0000        1.0    1.00    1.0000   1.0000
2              XGBoost    1.0000        1.0    1.00    1.0000   1.0000
3    Gradient Boosting    1.0000        1.0    1.00    1.0000   1.0000
4             AdaBoost    1.0000        1.0    1.00    1.0000   1.0000
5        Decision Tree    0.9875        1.0    0.98    0.9899   0.9900
6  Logistic Regression    0.9750        1.0    0.96    0.9796   0.9993
7                  SVM    0.9750        1.0    0.96    0.9796   1.0000
8                  KNN    0.9625        1.0    0.94    0.9691   0.9900

## 4. Final Test Evaluation After Tuning

                 Model  Accuracy  Precision  Recall      F1  ROC_AUC
0        Random Forest    1.0000     1.0000    1.00  1.0000   1.0000
1              XGBoost    1.0000     1.0000    1.00  1.0000   1.0000
2             LightGBM    1.0000     1.0000    1.00  1.0000   1.0000
3    Gradient Boosting    0.9875     0.9804    1.00  0.9901   1.0000
4        Decision Tree    0.9875     1.0000    0.98  0.9899   0.9900
5             AdaBoost    0.9875     1.0000    0.98  0.9899   1.0000
6                  SVM    0.9875     1.0000    0.98  0.9899   1.0000
7  Logistic Regression    0.9750     1.0000    0.96  0.9796   0.9993
8                  KNN    0.9625     1.0000    0.94  0.9691   0.9900

## 5. Tuning and Evaluation Combined

,Model,Best_CV_F1,Mean_Train_F1,Train_CV_Gap,Best_Params,Generalization_Diagnostic,Accuracy,Precision,Recall,F1,ROC_AUC
0,Random Forest,0.9951,0.9981,0.0031,"{'model__n_estimators': 75, 'model__min_sample...",No strong warning from train-CV gap,1.0000,1.0000,1.00,1.0000,1.0000
1,LightGBM,0.9874,1.0000,0.0126,"{'model__num_leaves': 31, 'model__n_estimators...",No strong warning from train-CV gap,1.0000,1.0000,1.00,1.0000,1.0000
2,XGBoost,0.9901,0.9988,0.0086,"{'model__subsample': 0.8, 'model__n_estimators...",No strong warning from train-CV gap,1.0000,1.0000,1.00,1.0000,1.0000
3,Gradient Boosting,0.9827,0.9957,0.0130,"{'model__n_estimators': 75, 'model__min_sample...",No strong warning from train-CV gap,0.9875,0.9804,1.00,0.9901,1.0000
4,AdaBoost,0.9925,1.0000,0.0075,"{'model__n_estimators': 50, 'model__learning_r...",No strong warning from train-CV gap,0.9875,1.0000,0.98,0.9899,1.0000
5,Decision Tree,0.9752,0.9975,0.0223,"{'model__min_samples_split': 2, 'model__min_sa...",No strong warning from train-CV gap,0.9875,1.0000,0.98,0.9899,0.9900
6,SVM,0.9949,1.0000,0.0051,"{'model__gamma': 0.1, 'model__C': 1.0}",No strong warning from train-CV gap,0.9875,1.0000,0.98,0.9899,1.0000
7,Logistic Regression,0.9951,1.0000,0.0049,"{'model__solver': 'lbfgs', 'model__C': 10.0}",No strong warning from train-CV gap,0.9750,1.0000,0.96,0.9796,0.9993
8,KNN,0.9793,0.9873,0.0081,"{'model__weights': 'uniform', 'model__p': 1, '...",No strong warning from train-CV gap,0.9625,1.0000,0.94,0.9691,0.9900

## 6. Dashboard Model Results

,Model,Training Accuracy,Training Precision,Training Recall,Training F1-Score,Training ROC-AUC,CV Mean Accuracy,CV Std,Generalization Gap
0,SVM,1.0000,1.0000,1.0,1.0000,1.0000,0.9969,0.0062,0.0031
1,Logistic Regression,1.0000,1.0000,1.0,1.0000,1.0000,0.9938,0.0077,0.0062
2,Random Forest,1.0000,1.0000,1.0,1.0000,1.0000,0.9906,0.0077,0.0094
3,AdaBoost,1.0000,1.0000,1.0,1.0000,1.0000,0.9906,0.0125,0.0094
4,LightGBM,1.0000,1.0000,1.0,1.0000,1.0000,0.9844,0.0171,0.0156
5,XGBoost,0.9969,0.9950,1.0,0.9975,1.0000,0.9812,0.0182,0.0156
6,Gradient Boosting,1.0000,1.0000,1.0,1.0000,1.0000,0.9750,0.0272,0.0250
7,KNN,1.0000,1.0000,1.0,1.0000,1.0000,0.9625,0.0125,0.0375
8,Decision Tree,0.9906,0.9852,1.0,0.9926,0.9993,0.9531,0.0171,0.0375